"""add paid_by to itinerary_item

Revision ID: 093074f849bc
Revises: d6eea980ecbe
Create Date: 2026-09-10 23:53:26.291306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '093074f849bc'
down_revision: Union[str, Sequence[str], None] = 'd6eea980ecbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    nullable 컬럼 추가뿐이라 백필이 필요 없고 기존 데이터에 영향이 없다
    (NULL = 결제자 미지정 = 정산에서 제외). 허용값("희경"/"재승")은 애플리케이션
    레벨에서만 검증하므로 DB CHECK 제약은 걸지 않는다 — 근거는 ADR-0006.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_item', schema=None) as batch_op:
        batch_op.drop_column('paid_by')

    # ### end Alembic commands ###
